spring:
  datasource:
    url: jdbc:mysql://localhost:3306/medical_system
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper2/*.xml  # ??Mapper.xml?????
  type-aliases-package: org.ms.medicalsystem.model  # ???????
  configuration:
    map-underscore-to-camel-case: true  # ????????

